### ISSUE TITLE
metrics name truncated

### ISSUE THREAD

**Issue by yiyijin** [orijtech/prometheus-go-metrics-exporter#4]
We are using opencensus to collect metrics from the application, which uses oc-agent and oc-collector to send to prometheus. 

I have noticed that the metrics name gets truncated if the number of chars is greater than 100, after looking at the code, it looks like: https://github.com/orijtech/prometheus-go-metrics-exporter/blob/b321c5297f6069b012947cfae5924a66c593ea60/sanitize.go#L25
is causing the issue. 

I just wonder any reason for this restriction? is there anyway that we can make it configurable?

**Comment by odeke-em** [comment]
Hello there @yiyijin! Thanks for filing this issue.

If I recall correctly from 2017/2019, this is to protect and high cardinality labels as the limit for label key names by OpenCensus or Stackdriver, but indeed it truncates long names.

Since Prometheus doesn't seem to have a limit, perhaps we can/could remove this limit?

**Comment by yiyijin** [comment]
@odeke-em Thanks a lot for the reply! I think it will be good to remove this limitations, or make it configurable at least, I just wonder do we have an estimate for this change? Thanks a lot!

**Comment by odeke-em** [comment]
Looks like Christmas came early for you @yiyijin :) I've mailed out PR https://github.com/orijtech/prometheus-go-metrics-exporter/pull/5 which I shall merge in shortly then make a release. I'll then make a PR to the OpenCensus Agent and after that is made, you'll be on your way to using it without truncation.

**Comment by yiyijin** [comment]
Thanks a lot!

**Comment by odeke-em** [comment]
Cheers! Thanks for the report, and for using this software!
